networks:
  public-network:
    driver: bridge

services:
  api:
    container_name: codechat_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8084:8084
    volumes:
      - ./instances:/codechat/instances
    env_file:
      - .env
    networks:
      - public-network
